export const QuotesConstants = [
  'Dream big, work hard.',
  'Stay hungry, stay foolish.',
  "Believe you can and you're halfway there.",
  'Do what you love, love what you do.',
  'Success is a journey, not a destination.',
  "Keep going, you're getting there.",
  'Every moment is a fresh beginning.',
  'Make today amazing.',
  'Start where you are, use what you have.',
  'You are stronger than you think.',
  'Stay positive, work hard, make it happen.',
  'Don’t stop until you’re proud.',
  'Doubt kills more dreams than failure ever will.',
  'Great things never come from comfort zones.',
  'Hustle, hit, never quit.',
  'Opportunities don’t happen, you create them.',
  'Do it with passion or not at all.',
  'It always seems impossible until it’s done.',
  'Success is the sum of small efforts repeated daily.',
  'Be yourself; everyone else is already taken.',
] as const;
